### ISSUE TITLE
Founded typos.

### ISSUE THREAD

**Issue by kangyeolk** [coding-pot/Zero2Story#36]
Hi, thank you for sharing this awesome work!
In background prompt part, the description and the example are different.

https://github.com/coding-pot/Zero2Story/blob/b93da7db9462b2fa2bd4b9dc479b955b15fec0ce/assets/palm_prompts.toml#L58

https://github.com/coding-pot/Zero2Story/blob/b93da7db9462b2fa2bd4b9dc479b955b15fec0ce/assets/palm_prompts.toml#L77

It should be modified as the same naming: `main_sentence` or `primary_sentence`

**Comment by jphan32** [comment]
Thank you for identifying and reporting the issue.
